import {requireAuth,supabase} from './_auth.js';
import {buildOccurrences,inferRule,isoAddDays,monthBounds,normalizeMonth,normalizeTime} from '../lib/agenda.js';
async function rest(path,options={},label='Falha no banco'){const r=await supabase('/rest/v1/'+path,options),data=await r.json().catch(()=>null);if(!r.ok){if(data?.code==='23505'&&/pacientes_nome_key/.test(data.message||''))throw new Error('Já existe um paciente cadastrado com esse nome.');throw new Error(`${label}: ${r.status}`);}return data;}
async function allSessions(){const rows=[];for(let from=0;;from+=1000){const page=await rest('sessoes?select=data_sessao,genero,faixa_etaria,modalidade,horario,comparecimento,motivo,valor_sessao,sessoes_cobradas,valor_total,valor_final,cnpj,comentario,pacientes!inner(nome,ativo),convenios(nome)&order=data_sessao.asc',{headers:{Range:`${from}-${from+999}`}},'Falha ao carregar sessões');rows.push(...page);if(page.length<1000)break;}return rows;}
async function allAgendaSessions(){const rows=[];for(let from=0;;from+=500){const page=await rest('sessoes?select=id,paciente_id,data_sessao,horario,comparecimento,convenio_id,modalidade,valor_sessao&order=data_sessao.asc',{headers:{Range:`${from}-${from+499}`}},'Falha ao carregar histórico');rows.push(...page);if(page.length<500)break;}return rows;}
const DIA_ABREV=['','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
// Mesmo formato da "chave concatenada" que os pacientes legados ja tinham
// (ex: "Leonice | Ter 09h", vindo da planilha) -- sem isso o paciente cadastrado
// pela Agenda aparecia so com o nome cru nos dropdowns de Prontuarios/Documentos.
function rotuloAgenda(nome,diaSemana,horario){
  const primeiroNome=String(nome||'').trim().split(/\s+/)[0]||'';
  const [h,m]=String(horario||'').split(':');
  if(!h)return primeiroNome;
  // h já vem com dois dígitos ("09") -- NÃO usar Number(h) aqui, senão vira "9h"
  // em vez de "09h" (padrão da planilha legada, ex.: "Ter 09h", "Sex 07h30").
  const horaLabel=h+'h'+(m&&m!=='00'?m:'');
  return primeiroNome+' | '+(DIA_ABREV[diaSemana]||'')+' '+horaLabel;
}
function mesesSeguintes(mesInicial,n){const out=[];let[y,m]=mesInicial.split('-').map(Number);for(let i=0;i<n;i++){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++;}}return out;}
function historicalStatus(value,date){if(String(date)>=agendaToday())return'agendado';const v=String(value||'').toLowerCase();if(/cancel/.test(v))return'cancelado';if(/falta|faltou|ausente|não compareceu|nao compareceu/.test(v))return'falta';return'realizado';}
function brDate(v){const[y,m,d]=String(v).split('-');return`${d}/${m}/${y}`;}function agendaToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=t=>parts.find(x=>x.type===t)?.value;return`${get('year')}-${get('month')}-${get('day')}`;}function text(v,max=160){const s=String(v||'').trim();if(!s||s.length>max)throw new Error('Campo obrigatório inválido');return s;}function status(v){return['ativo','pausado','inativo'].includes(v)?v:'ativo';}
async function state(month){const{first,last}=monthBounds(month);const[patients,rules,appointments,insurances]=await Promise.all([rest('pacientes?select=id,nome,ativo,status_operacional,pausado_ate,inativo_em,contabiliza_cnpj,atualizado_em&order=nome.asc'),rest('recorrencias_atendimento?select=*&ativo=eq.true&order=vigencia_inicio.desc'),rest(`agenda_atendimentos?select=*,pacientes(nome,status_operacional),convenios(nome),sessoes(sessoes_cobradas,sessao_consumida,valor_final,comentario)&data_atendimento=gte.${first}&data_atendimento=lte.${last}&order=data_atendimento.asc,horario.asc`),rest('convenios?select=id,nome&ativo=eq.true&order=nome.asc')]);return{month,patients,rules,appointments,insurances};}
async function agenda(req,res){
 if(req.method==='GET')return res.status(200).json(await state(normalizeMonth(req.query.month||new Date().toISOString().slice(0,7))));
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};
 if(b.action==='save_patient'){const st=status(b.status),payload={nome:text(b.nome,120),status_operacional:st,ativo:st==='ativo',pausado_ate:st==='pausado'&&b.pausado_ate?b.pausado_ate:null,inativo_em:st==='inativo'?new Date().toISOString():null,contabiliza_cnpj:!!b.contabiliza_cnpj,atualizado_em:new Date().toISOString()};let rows;if(b.id)rows=await rest(`pacientes?id=eq.${encodeURIComponent(b.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)},'Falha ao atualizar paciente');else rows=await rest('pacientes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...payload,ultima_chave:payload.nome,ultimo_label:payload.nome})},'Falha ao cadastrar paciente');const patient=rows[0];if(st!=='ativo'&&b.cancel_future){const today=new Date().toISOString().slice(0,10);await rest(`agenda_atendimentos?paciente_id=eq.${patient.id}&data_atendimento=gte.${today}&status=eq.agendado`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'cancelado',atualizado_em:new Date().toISOString()})});}return res.status(200).json(patient);}
 if(b.action==='patient_history'){const id=text(b.paciente_id,80);const rows=await rest(`recorrencias_atendimento?select=*&paciente_id=eq.${encodeURIComponent(id)}&order=vigencia_inicio.desc`,{},'Falha ao carregar histórico do paciente');return res.status(200).json(rows);}
 if(b.action==='save_recurrence'){const id=text(b.paciente_id,80),freq=String(b.frequencia||''),day=Number(b.dia_semana),start=text(b.vigencia_inicio,10),time=text(b.horario,5),valorSessao=Number(b.valor_sessao||0);if(!['semanal','quinzenal'].includes(freq))throw new Error('Frequência inválida');if(!Number.isInteger(day)||day<1||day>7)throw new Error('Dia da semana inválido');const current=await rest(`recorrencias_atendimento?select=id,vigencia_inicio&paciente_id=eq.${id}&ativo=eq.true`);for(const r of current){if(r.vigencia_inicio<start)await rest(`recorrencias_atendimento?id=eq.${r.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({ativo:false,vigencia_fim:isoAddDays(start,-1),atualizado_em:new Date().toISOString()})});else await rest(`recorrencias_atendimento?id=eq.${r.id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});}let plano=null;if(valorSessao>0){const planoRows=await rest('rpc/obter_ou_criar_plano_pacote',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({p_valor_sessao:valorSessao})},'Falha ao associar pacote');plano=Array.isArray(planoRows)?planoRows[0]:planoRows;}const rows=await rest('recorrencias_atendimento',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({paciente_id:id,frequencia:freq,dia_semana:day,horario:time,vigencia_inicio:start,convenio_id:b.convenio_id||null,modalidade:String(b.modalidade||'').trim()||null,valor_sessao:valorSessao,plano_pacote_id:plano?.id||null,ativo:true,origem:'manual'})},'Falha ao salvar recorrência');const paciente=await rest(`pacientes?select=nome&id=eq.${encodeURIComponent(id)}`);if(paciente[0])await rest(`pacientes?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({ultimo_label:rotuloAgenda(paciente[0].nome,day,time),atualizado_em:new Date().toISOString()})});
  // Ao mudar frequência/dia/horário, os atendimentos "agendado" futuros gerados
  // pela regra ANTIGA continuavam na agenda (ex.: paciente vira quinzenal mas
  // segue aparecendo toda semana -- ver Yasmin Garcia). Limpa os futuros ainda
  // não liquidados gerados por recorrência a partir da nova vigência e regera
  // pelos próximos 3 meses com a regra nova. Atendimentos avulsos (origem
  // 'manual') e já liquidados não são tocados.
  const regra=rows[0],hoje=agendaToday(),limpar=start>hoje?start:hoje;
  await rest(`agenda_atendimentos?paciente_id=eq.${encodeURIComponent(id)}&status=eq.agendado&sessao_id=is.null&origem=eq.recorrencia&data_atendimento=gte.${limpar}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});
  const regen=[];
  for(const mes of mesesSeguintes(hoje.slice(0,7),3))for(const date of buildOccurrences(regra,mes)){if(date<limpar)continue;regen.push({paciente_id:id,recorrencia_id:regra.id,data_atendimento:date,horario:regra.horario,status:'agendado',convenio_id:regra.convenio_id,modalidade:regra.modalidade,valor_previsto:regra.valor_sessao,origem:'recorrencia'});}
  if(regen.length)await rest('agenda_atendimentos?on_conflict=paciente_id,data_atendimento,horario',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(regen)},'Falha ao regenerar agenda');
  return res.status(200).json({...rows[0],plano_pacote_nome:plano?.nome||null});}
 if(b.action==='infer_recurrences'){const cutoff=isoAddDays(new Date().toISOString().slice(0,10),-180),[patients,sessions,existing]=await Promise.all([rest('pacientes?select=id,ativo,status_operacional&ativo=eq.true'),rest(`sessoes?select=paciente_id,data_sessao,horario,modalidade,valor_sessao,convenio_id&data_sessao=gte.${cutoff}&order=data_sessao.asc`),rest('recorrencias_atendimento?select=paciente_id&ativo=eq.true')]),known=new Set(existing.map(x=>x.paciente_id)),allowed=new Set(patients.filter(x=>(x.status_operacional||'ativo')==='ativo').map(x=>x.id)),groups=new Map();sessions.forEach(r=>{if(allowed.has(r.paciente_id)&&!known.has(r.paciente_id)){if(!groups.has(r.paciente_id))groups.set(r.paciente_id,[]);groups.get(r.paciente_id).push(r);}});let created=0;for(const[id,rows]of groups){const rule=inferRule(rows);if(!rule||rule.confianca<.5)continue;const last=rows.at(-1);await rest('recorrencias_atendimento',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({paciente_id:id,frequencia:rule.frequencia,dia_semana:rule.dia_semana,horario:rule.horario,vigencia_inicio:rule.vigencia_inicio,convenio_id:last.convenio_id||null,modalidade:last.modalidade||null,valor_sessao:Number(last.valor_sessao||0),ativo:true,origem:'inferido'})});created++;}return res.status(200).json({created});}
 if(b.action==='seed_history'){const sessions=await allAgendaSessions(),raw=sessions.filter(x=>x.paciente_id&&/^\d{4}-\d{2}-\d{2}$/.test(String(x.data_sessao||''))&&String(x.data_sessao)<agendaToday()).map(x=>({sessao_id:x.id,paciente_id:x.paciente_id,data_atendimento:x.data_sessao,horario:normalizeTime(x.horario),status:historicalStatus(x.comparecimento,x.data_atendimento),convenio_id:x.convenio_id||null,modalidade:x.modalidade||null,valor_previsto:Number(x.valor_sessao||0),origem:'historico'})),rows=[...new Map(raw.map(x=>[x.paciente_id+'|'+x.data_atendimento+'|'+x.horario,x])).values()];for(let i=0;i<rows.length;i+=200)await rest('agenda_atendimentos?on_conflict=sessao_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows.slice(i,i+200))},'Falha ao importar histórico');return res.status(200).json({processed:rows.length,collapsed:raw.length-rows.length,missing_time:rows.filter(x=>x.horario==='00:00').length,skipped:sessions.length-raw.length});}
 if(b.action==='generate_month'){const month=normalizeMonth(b.month),rules=await rest('recorrencias_atendimento?select=*,pacientes!inner(ativo,status_operacional)&ativo=eq.true&pacientes.ativo=eq.true'),rows=[];for(const r of rules){if((r.pacientes?.status_operacional||'ativo')!=='ativo')continue;for(const date of buildOccurrences(r,month))rows.push({paciente_id:r.paciente_id,recorrencia_id:r.id,data_atendimento:date,horario:r.horario,status:'agendado',convenio_id:r.convenio_id,modalidade:r.modalidade,valor_previsto:r.valor_sessao,origem:'recorrencia'});}if(rows.length)await rest('agenda_atendimentos?on_conflict=paciente_id,data_atendimento,horario',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)},'Falha ao gerar agenda');return res.status(200).json({generated:rows.length});}
 if(b.action==='add_appointment'){const paciente_id=text(b.paciente_id,80),data_atendimento=text(b.data_atendimento,10),horario=normalizeTime(text(b.horario,5));if(!/^\d{4}-\d{2}-\d{2}$/.test(data_atendimento))throw new Error('Data inválida');const rows=await rest('agenda_atendimentos?on_conflict=paciente_id,data_atendimento,horario',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify({paciente_id,data_atendimento,horario,status:'agendado',origem:'manual',valor_previsto:0})},'Falha ao adicionar atendimento');if(!rows.length)throw new Error('Já existe um atendimento para esse paciente nessa data e horário.');return res.status(200).json(rows[0]);}
 if(b.action==='settle_appointment'){const id=text(b.id,80),st=String(b.status||''),charged=Number(b.sessoes_cobradas||0),received=Number(b.valor_recebido||0);if(!['realizado','falta','cancelado'].includes(st))throw new Error('Escolha o resultado do atendimento');if(![charged,received].every(Number.isFinite)||charged<0||received<0)throw new Error('Valores de cobrança inválidos');const consumed=st==='realizado'?1:0;const comentario=String(b.comentario||'').trim().slice(0,500)||null;const row=await rest('rpc/finalizar_agenda_atendimento',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({p_agenda_id:id,p_status:st,p_sessoes_consumidas:consumed,p_sessoes_cobradas:charged,p_valor_recebido:received,p_comentario:comentario})},'Falha ao confirmar atendimento');return res.status(200).json(Array.isArray(row)?row[0]:row);}
 if(b.action==='update_appointment'){const id=text(b.id,80),payload={atualizado_em:new Date().toISOString()};if(['agendado','realizado','falta','cancelado'].includes(b.status))payload.status=b.status;const rows=await rest(`agenda_atendimentos?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)},'Falha ao atualizar atendimento');return res.status(200).json(rows[0]);}
 if(b.action==='delete_patient'){const id=text(b.id,80),nome=text(b.nome_confirmacao,120),patient=await rest(`pacientes?select=nome&id=eq.${encodeURIComponent(id)}`);if(!patient.length)throw new Error('Paciente não encontrado');if(patient[0].nome.trim().toLowerCase()!==nome.trim().toLowerCase())throw new Error('Nome de confirmação não confere');await rest('rpc/excluir_paciente_definitivo',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({p_paciente_id:id})},'Falha ao excluir paciente');return res.status(200).json({deleted:true});}
 throw new Error('Ação inválida');
}
async function sessions(req,res){
 if(req.method==='GET'){
  const month=normalizeMonth(req.query.month||new Date().toISOString().slice(0,7)),{first,last}=monthBounds(month);
  let path=`sessoes?select=id,paciente_id,data_sessao,horario,modalidade,comparecimento,sessoes_cobradas,valor_sessao,valor_final,comentario,pacientes(nome),convenios(nome)&data_sessao=gte.${first}&data_sessao=lte.${last}&order=data_sessao.asc,horario.asc`;
  if(req.query.paciente_id)path+=`&paciente_id=eq.${encodeURIComponent(req.query.paciente_id)}`;
  return res.status(200).json(await rest(path,{},'Falha ao carregar atendimentos'));
 }
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};
 if(b.action==='update_session'){
  const id=text(b.id,80),comparecimento=['Sim','Não','Cancelado'].includes(b.comparecimento)?b.comparecimento:null;
  if(!comparecimento)throw new Error('Comparecimento inválido');
  const cobradas=Number(b.sessoes_cobradas||0),final=Number(b.valor_final||0);
  if(![cobradas,final].every(Number.isFinite)||cobradas<0||final<0)throw new Error('Valores inválidos');
  const comentario=String(b.comentario||'').trim().slice(0,500)||null;
  const rows=await rest(`sessoes?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({comparecimento,sessoes_cobradas:cobradas,sessao_consumida:comparecimento==='Sim'?1:0,valor_final:final,comentario,atualizado_em:new Date().toISOString()})},'Falha ao atualizar atendimento');
  return res.status(200).json(rows[0]);
 }
 throw new Error('Ação inválida');
}
export default async function handler(req,res){if(!await requireAuth(req,res))return;req.query=req.query||{};try{if(req.query.resource==='agenda')return await agenda(req,res);if(req.query.resource==='sessions')return await sessions(req,res);if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const rows=await allSessions();return res.status(200).json(rows.map(r=>({'Data':brDate(r.data_sessao),'Paciente':r.pacientes.nome,'Gênero':r.genero||'','Faixa Etária':r.faixa_etaria||'','Modalidade':r.modalidade||'','Convênio':r.convenios?.nome||'','Horário':r.horario||'','Valor da sessão':r.valor_sessao,'Sessões cobradas':r.sessoes_cobradas,'Valor total':r.valor_total,'Valor final':r.valor_final,'Ativo':r.pacientes.ativo?'Ativo':'','Comparecimento':r.comparecimento||'','Motivo':r.motivo||'','CNPJ?':r.cnpj?'Sim':'Não','Comentário':r.comentario||''})));}catch(e){return res.status(/inválid|obrigatór/i.test(e.message)?400:500).json({error:e.message||'Não foi possível concluir'});}}
